### ISSUE TITLE
Update Dockerfiles

### ISSUE THREAD

**Issue by vusause** [wizeline/wizelink-front#23]
Previously the frontend ran on Webpack Dev Server `localhost:8080` and was Dockerized in one container. Now there is that and a small express server running on `localhost:9090` to test the frontend components.

As a developer I need to sometimes develop in an container. Please add another Dockerfile for the express server utility and use `docker-compose` to run the containers together.

**Comment by zxul767** [comment]
@vusause I wonder if we really need to be running the small express server. Did you consider just having a gateway class that can be mocked, so the code in `src/actions/actions.js` doesn't really know the details of how stuff is fetched from the backend? Basically, replacing:

```javascript
    fetch(API + '/getTags', config)
    .then(response => response.json())
    .then(response =>
      dispatch({
        type: GET_TAGS,
        payload: response,
      }),
    )
```

with something like:

```javascript
    tagsService.getTagsFor(url)
    .then(jsonResponse =>
      dispatch({
        type: GET_TAGS,
        payload: jsonResponse,
      }),
    )
```
